### ISSUE TITLE
Fix serialisation of UserStorageProvider config

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak-ui#3341]
I'm afraid this is not yet finally fixed with `19.0.2` and should be re-opened (or should I create a new issue for it?).

While the dynamic fields are now properly rendered and filled with data, it's not possible to edit and submit data to the server. There is an exception thrown:
```
2022-09-14 10:57:28,941 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-5) Uncaught server error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('https://kze2nq1l79.execute-api.eu-central-1.amazonaws.com/peanuts')
kcd_kc    |  at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 74] (through reference chain: org.keycloak.representations.idm.ComponentRepresentation["config"]->org.keycloak.common.util.MultivaluedHashMap["peanutsBaseUrl"])
kcd_kc    | 	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
kcd_kc    | 	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1728)
kcd_kc    | 	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1353)
kcd_kc    | 	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
kcd_kc    | 	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.handleNonArray(StringCollectionDeserializer.java:284)
kcd_kc    | 	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:192)
kcd_kc    | 	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:182)
kcd_kc    | 	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:25)
kcd_kc    | 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:609)
kcd_kc    | 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:437)
kcd_kc    | 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
kcd_kc    | 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
kcd_kc    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
kcd_kc    | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
kcd_kc    | 	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
kcd_kc    | 	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2025)
kcd_kc    | 	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1175)
...
```

When comparing the payload which is sent from the UI to the server between old and new UI, I get the following:

**Old UI:**
```
{
    "name": "peanuts",
    "providerId": "peanuts-user-provider",
    "providerType": "org.keycloak.storage.UserStorageProvider",
    "parentId": "demo",
    "config": {
        "enabled": [
            "true"
        ],
        "cachePolicy": [
            "DEFAULT"
        ],
        "peanutsBaseUrl": [
            "https://someid.execute-api.eu-central-1.amazonaws.com/peanuts"
        ],
        "peanutsAuthUsername": [
            "peanuts"
        ],
        "peanutsAuthPassword": [
            "s3cr3t"
        ]
    }
}
```

**New UI:**
```
{
    "name": "peanuts",
    "config": {
        "peanutsBaseUrl": "https://someid.execute-api.eu-central-1.amazonaws.com/peanuts",
        "peanutsAuthUsername": "peanuts",
        "peanutsAuthPassword": "s3cr3t",
        "enabled": [
            "true"
        ],
        "cachePolicy": [
            "DEFAULT"
        ]
    },
    "providerId": "peanuts-user-provider",
    "providerType": "org.keycloak.storage.UserStorageProvider",
    "parentId": "demo"
}
```

So, the custom properties (in the example starting with "peanuts...", must be submitted as a string array, not a pure string.
Please check this also for all other types, not only for strings.

Thanks.

_Originally posted by @dasniko in https://github.com/keycloak/keycloak-ui/issues/2989#issuecomment-1246611796_

**Comment by nisha-ns** [comment]
When this is planned to be fixed?

**Comment by Neeya123** [comment]
I see this issue is fixed. Will this fix be released sooner?

**Comment by edewit** [comment]
It will be part of the next release

**Comment by Neeya123** [comment]
When is next release? Sorry we are waiting for this.

**Comment by Neeya123** [comment]
This issue is fixed but not yet been released in latest version 19.0.3? When this is planned to be released?

**Comment by edewit** [comment]
this issue is fixed in a [nightly version](https://github.com/keycloak/keycloak/releases/tag/nightly) and will be in the released by v20.0.0.

**Comment by ssilvert** [comment]
@Neeya123 Version 20.0.0 should be out in 1 to 2 weeks.

**Comment by robert-franz** [comment]
Is there a plan to deliver that in e.g. a 19.0.4?

**Comment by jonkoops** [comment]
No, it will be included in 20. We currently have no intention of shipping another patch release.

**Comment by xtreme-uz** [comment]
I managed to bypass the error temporarily by setting keycloak instead of keyckoak.v2 in Admin console theme, After successfully installing user federation, I rolled back the process.

**Comment by raphisuter** [comment]
I think this is also related to this issue in some kind? I think this is the same issue in the latest version V20 https://github.com/keycloak/keycloak/issues/16640
