### ISSUE TITLE
Flow Item Config property setting Dialog UI error

### ISSUE THREAD

**Issue by cooper-lyt** [keycloak/keycloak-ui#3432]
### Describe the bug

Any Flow item change config property value, after reopen config dialog, value display error.

### Version

19.0.1

### Expected behavior

show property value

### Actual behavior

value is empty

### How to Reproduce?

Authentication > Any Flow > Open any config Dialog > input value > save > reopen dialog > value is empty!

if input a new value then throw exception.

### Anything else?

example:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/4219608/183958793-014dcd9a-4de2-4500-a33c-a1d8b4a2477e.png">

save and reopen:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/4219608/183958915-8610bce1-2ffe-4ea5-80d6-e1ebad786fee.png">

input a new value And save:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/4219608/183959217-5ab75291-46e6-4987-bb53-d9c8b0c11614.png">

**Comment by DanielScholte** [comment]
Was this supposed to be fixed in `19.0.2` as described in the linked issue?  
I'm currently running `19.0.2` and still experiencing errors when using `MULTIVALUED_STRING_TYPE` for the configuration of an authentication flow step.  
  
I get a notification:
![image](https://user-images.githubusercontent.com/22204349/192809136-82ddfafa-dc9e-4288-89bf-8eae97fec814.png)

And the API throws the following stacktrace:
```
2022-09-28 14:41:33,813 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-14) Uncaught server error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 64] (through reference chain: org.keycloak.representations.idm.AuthenticatorConfigRepresentation["config"]->java.util.LinkedHashMap["validDomains"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:222)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:46)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:609)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:437)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2025)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1175)
```  
  
This happens when creating a new step (and thus creating a new configuration entry) and when editing an existing step.
