### ISSUE TITLE
`kc.sh build` fails with added/modified keycloak-admin-ui jar

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak-ui#3716]
### Describe the bug

If you modify the `admin-ui` project, build the jar using `keycloak-theme`, add that jar to the `providers` dir of your keycloak distribution, and run `kc.sh build`, it fails. This appears to be because of the new Resources.

### Version

20.0.0

### Expected behavior

It should build as before.

### Actual behavior

```
[garth:keycloak-ui ((20.0.0))]$ docker build -t ui-test:latest -f Dockerfile .
[+] Building 37.5s (7/11)
 => [internal] load build definition from Dockerfile                                                          0.0s
 => => transferring dockerfile: 827B                                                                          0.0s
 => [internal] load .dockerignore                                                                             0.0s
 => => transferring context: 2B                                                                               0.0s
 => [internal] load metadata for quay.io/keycloak/keycloak:20.0.0                                             1.3s
 => [builder 1/3] FROM quay.io/keycloak/keycloak:20.0.0@sha256:18ed0fbf70e80643ec205fda93c48492d7268e087344  22.7s
 => => resolve quay.io/keycloak/keycloak:20.0.0@sha256:18ed0fbf70e80643ec205fda93c48492d7268e0873443bb46ddcc  0.0s
 => => sha256:2f6ddcd3abd0e3ea92ddfa06a7620ce654f467d186bd37316664aa93dbf50872 87.24MB / 87.24MB              4.2s
 => => sha256:18ed0fbf70e80643ec205fda93c48492d7268e0873443bb46ddcce7a7638942d 741B / 741B                    0.0s
 => => sha256:af1e2bdb51e04b32217731c4ee7f6f968c63c8c8b2298b5940fbc8c1bc7f557e 954B / 954B                    0.0s
 => => sha256:27293f6101151725e179bfc7a6bdd5c4a3a1edc25362d88ef8c269f48ced2320 8.31kB / 8.31kB                0.0s
 => => sha256:cda5011080e257779a602c373f53014e09c12b7f4ac76eb8935590d0dc451ef3 172.42MB / 172.42MB           12.3s
 => => extracting sha256:cda5011080e257779a602c373f53014e09c12b7f4ac76eb8935590d0dc451ef3                     4.1s
 => => extracting sha256:2f6ddcd3abd0e3ea92ddfa06a7620ce654f467d186bd37316664aa93dbf50872                     5.9s
 => [internal] load build context                                                                             0.3s
 => => transferring context: 5.71MB                                                                           0.3s
 => [builder 2/3] COPY ./keycloak-theme/target/*.jar /opt/keycloak/providers/                                 0.7s
 => ERROR [builder 3/3] RUN /opt/keycloak/bin/kc.sh --verbose build                                          12.7s
------
 > [builder 3/3] RUN /opt/keycloak/bin/kc.sh --verbose build:
#7 1.881 Changes detected in configuration. Updating the server image.
#7 1.937 Updating the configuration and installing your custom providers, if any. Please wait.
#7 12.54 ERROR: Failed to run 'build' command.
#7 12.54 Error details:
#7 12.54 java.lang.reflect.InvocationTargetException
#7 12.54 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#7 12.54 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#7 12.54 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#7 12.54 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#7 12.54 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:84)
#7 12.54 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
#7 12.54 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
#7 12.54 	at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:71)
#7 12.54 	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
#7 12.54 	at picocli.CommandLine.access$1300(CommandLine.java:145)
#7 12.54 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
#7 12.54 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
#7 12.54 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
#7 12.54 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
#7 12.54 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
#7 12.54 	at picocli.CommandLine.execute(CommandLine.java:2078)
#7 12.54 	at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentation(Picocli.java:183)
#7 12.54 	at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:120)
#7 12.54 	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:88)
#7 12.54 	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
#7 12.54 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#7 12.54 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#7 12.54 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#7 12.54 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#7 12.54 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
#7 12.54 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
#7 12.54 Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
#7 12.54 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 4 deployment problems:
#7 12.54 [1] Unsatisfied dependency for type org.keycloak.models.RealmModel and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.BruteForceUsersResource():realm
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.BruteForceUsersResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.BruteForceUsersResource]
#7 12.54 [2] Unsatisfied dependency for type org.keycloak.services.resources.admin.permissions.AdminPermissionEvaluator and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.BruteForceUsersResource():auth
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.BruteForceUsersResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.BruteForceUsersResource]
#7 12.54 [3] Unsatisfied dependency for type org.keycloak.models.RealmModel and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.AuthenticationManagementResource():realm
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.AuthenticationManagementResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.AuthenticationManagementResource]
#7 12.54 [4] Unsatisfied dependency for type org.keycloak.services.resources.admin.permissions.AdminPermissionEvaluator and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.AuthenticationManagementResource():auth
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.AuthenticationManagementResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.AuthenticationManagementResource]
#7 12.54 	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1225)
#7 12.54 	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:287)
#7 12.54 	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:143)
#7 12.54 	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:517)
#7 12.54 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#7 12.54 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#7 12.54 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#7 12.54 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#7 12.54 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
#7 12.54 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
#7 12.54 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#7 12.54 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
#7 12.54 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
#7 12.54 	at java.base/java.lang.Thread.run(Thread.java:829)
#7 12.54 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
#7 12.54 	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.keycloak.models.RealmModel and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.BruteForceUsersResource():realm
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.BruteForceUsersResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.BruteForceUsersResource]
#7 12.54 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:440)
#7 12.54 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:539)
#7 12.54 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
#7 12.54 		... 13 more
#7 12.54 	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.keycloak.services.resources.admin.permissions.AdminPermissionEvaluator and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.BruteForceUsersResource():auth
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.BruteForceUsersResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.BruteForceUsersResource]
#7 12.54 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:440)
#7 12.54 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:539)
#7 12.54 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
#7 12.54 		... 13 more
#7 12.54 	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.keycloak.models.RealmModel and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.AuthenticationManagementResource():realm
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.AuthenticationManagementResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.AuthenticationManagementResource]
#7 12.54 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:440)
#7 12.54 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:539)
#7 12.54 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
#7 12.54 		... 13 more
#7 12.54 	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.keycloak.services.resources.admin.permissions.AdminPermissionEvaluator and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.AuthenticationManagementResource():auth
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.AuthenticationManagementResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.AuthenticationManagementResource]
#7 12.54 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:440)
#7 12.54 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:539)
#7 12.54 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
#7 12.54 		... 13 more
#7 12.54
#7 12.54 	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
#7 12.54 	at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:175)
#7 12.54 	at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)
#7 12.54 	... 26 more
#7 12.54 Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
#7 12.54 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 4 deployment problems:
#7 12.54 [1] Unsatisfied dependency for type org.keycloak.models.RealmModel and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.BruteForceUsersResource():realm
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.BruteForceUsersResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.BruteForceUsersResource]
#7 12.54 [2] Unsatisfied dependency for type org.keycloak.services.resources.admin.permissions.AdminPermissionEvaluator and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.BruteForceUsersResource():auth
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.BruteForceUsersResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.BruteForceUsersResource]
#7 12.54 [3] Unsatisfied dependency for type org.keycloak.models.RealmModel and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.AuthenticationManagementResource():realm
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.AuthenticationManagementResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.AuthenticationManagementResource]
#7 12.54 [4] Unsatisfied dependency for type org.keycloak.services.resources.admin.permissions.AdminPermissionEvaluator and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.AuthenticationManagementResource():auth
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.AuthenticationManagementResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.AuthenticationManagementResource]
#7 12.54 	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1225)
#7 12.54 	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:287)
#7 12.54 	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:143)
#7 12.54 	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:517)
#7 12.54 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#7 12.54 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#7 12.54 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#7 12.54 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#7 12.54 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
#7 12.54 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
#7 12.54 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#7 12.54 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
#7 12.54 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
#7 12.54 	at java.base/java.lang.Thread.run(Thread.java:829)
#7 12.54 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
#7 12.54 	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.keycloak.models.RealmModel and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.BruteForceUsersResource():realm
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.BruteForceUsersResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.BruteForceUsersResource]
#7 12.54 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:440)
#7 12.54 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:539)
#7 12.54 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
#7 12.54 		... 13 more
#7 12.54 	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.keycloak.services.resources.admin.permissions.AdminPermissionEvaluator and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.BruteForceUsersResource():auth
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.BruteForceUsersResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.BruteForceUsersResource]
#7 12.54 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:440)
#7 12.54 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:539)
#7 12.54 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
#7 12.54 		... 13 more
#7 12.54 	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.keycloak.models.RealmModel and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.AuthenticationManagementResource():realm
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.AuthenticationManagementResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.AuthenticationManagementResource]
#7 12.54 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:440)
#7 12.54 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:539)
#7 12.54 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
#7 12.54 		... 13 more
#7 12.54 	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.keycloak.services.resources.admin.permissions.AdminPermissionEvaluator and qualifiers [@Default]
#7 12.54 	- java member: org.keycloak.admin.ui.rest.AuthenticationManagementResource():auth
#7 12.54 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.AuthenticationManagementResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.AuthenticationManagementResource]
#7 12.54 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:440)
#7 12.54 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:539)
#7 12.54 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
#7 12.54 		... 13 more
#7 12.54
#7 12.55 	at io.quarkus.builder.Execution.run(Execution.java:123)
#7 12.55 	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
#7 12.55 	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
#7 12.55 	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
#7 12.55 	... 28 more
#7 12.55 Caused by: javax.enterprise.inject.spi.DeploymentException: Found 4 deployment problems:
#7 12.55 [1] Unsatisfied dependency for type org.keycloak.models.RealmModel and qualifiers [@Default]
#7 12.55 	- java member: org.keycloak.admin.ui.rest.BruteForceUsersResource():realm
#7 12.55 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.BruteForceUsersResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.BruteForceUsersResource]
#7 12.55 [2] Unsatisfied dependency for type org.keycloak.services.resources.admin.permissions.AdminPermissionEvaluator and qualifiers [@Default]
#7 12.55 	- java member: org.keycloak.admin.ui.rest.BruteForceUsersResource():auth
#7 12.55 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.BruteForceUsersResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.BruteForceUsersResource]
#7 12.55 [3] Unsatisfied dependency for type org.keycloak.models.RealmModel and qualifiers [@Default]
#7 12.55 	- java member: org.keycloak.admin.ui.rest.AuthenticationManagementResource():realm
#7 12.55 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.AuthenticationManagementResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.AuthenticationManagementResource]
#7 12.55 [4] Unsatisfied dependency for type org.keycloak.services.resources.admin.permissions.AdminPermissionEvaluator and qualifiers [@Default]
#7 12.55 	- java member: org.keycloak.admin.ui.rest.AuthenticationManagementResource():auth
#7 12.55 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.AuthenticationManagementResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.AuthenticationManagementResource]
#7 12.55 	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1225)
#7 12.55 	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:287)
#7 12.55 	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:143)
#7 12.55 	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:517)
#7 12.55 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#7 12.55 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#7 12.55 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#7 12.55 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
#7 12.55 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
#7 12.55 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
#7 12.55 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
#7 12.55 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
#7 12.55 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
#7 12.55 	at java.base/java.lang.Thread.run(Thread.java:829)
#7 12.55 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
#7 12.55 	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.keycloak.models.RealmModel and qualifiers [@Default]
#7 12.55 	- java member: org.keycloak.admin.ui.rest.BruteForceUsersResource():realm
#7 12.55 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.BruteForceUsersResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.BruteForceUsersResource]
#7 12.55 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:440)
#7 12.55 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:539)
#7 12.55 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
#7 12.55 		... 13 more
#7 12.55 	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.keycloak.services.resources.admin.permissions.AdminPermissionEvaluator and qualifiers [@Default]
#7 12.55 	- java member: org.keycloak.admin.ui.rest.BruteForceUsersResource():auth
#7 12.55 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.BruteForceUsersResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.BruteForceUsersResource]
#7 12.55 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:440)
#7 12.55 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:539)
#7 12.55 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
#7 12.55 		... 13 more
#7 12.55 	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.keycloak.models.RealmModel and qualifiers [@Default]
#7 12.55 	- java member: org.keycloak.admin.ui.rest.AuthenticationManagementResource():realm
#7 12.55 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.AuthenticationManagementResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.AuthenticationManagementResource]
#7 12.55 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:440)
#7 12.55 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:539)
#7 12.55 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
#7 12.55 		... 13 more
#7 12.55 	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.keycloak.services.resources.admin.permissions.AdminPermissionEvaluator and qualifiers [@Default]
#7 12.55 	- java member: org.keycloak.admin.ui.rest.AuthenticationManagementResource():auth
#7 12.55 	- declared on CLASS bean [types=[org.keycloak.admin.ui.rest.AuthenticationManagementResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.keycloak.admin.ui.rest.AuthenticationManagementResource]
#7 12.55 		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:440)
#7 12.55 		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:539)
#7 12.55 		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:275)
#7 12.55 		... 13 more
------
executor failed running [/bin/sh -c /opt/keycloak/bin/kc.sh --verbose build]: exit code: 1
```

### How to Reproduce?

1. Clone this repo
2. `git checkout 20.0.0`
3. `cd keycloak-theme`
4. `mvn clean install`
5. `cd ..`
6. Add this `Dockerfile`:
```
FROM quay.io/keycloak/keycloak:20.0.0 as builder

COPY ./keycloak-theme/target/*.jar /opt/keycloak/providers/

RUN /opt/keycloak/bin/kc.sh --verbose build

FROM quay.io/keycloak/keycloak:20.0.0

COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
COPY --from=builder /opt/keycloak/providers/ /opt/keycloak/providers/

WORKDIR /opt/keycloak
```
7. `docker build -t ui-test:latest -f Dockerfile .`

**Comment by xgp** [comment]
For anyone who's experiencing this, a temporary workaround is to just exclude the class files from the jar. They'll be available and loaded because of the presence of the default admin ui lib in the Keycloak distribution. Removing them here simply packages the theme without the classes.
```xml
    <build>
      <plugins>
        <!-- add this plugin to your pom -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.3.0</version>
          <configuration>
            <excludes>
              <!-- exclude the java extensions, as they're already there -->
              <exclude>**/*.class</exclude>
            </excludes>
          </configuration>
        </plugin>
        ...
```

Would it be a good permanent solution to have them packaged separately?

**Comment by Ekouyoja** [comment]
Thanks for the workaround
I was able to RUN /opt/keycloak/bin/kc.sh --verbose build but it seems that it does not overwrite the existing admin-ui or have miss something.

**Comment by xgp** [comment]
@Ekouyoja I also named my theme differently. I don't know if that made the difference. That involved:
1. changing the name in `keycloak-theme/src/main/resources/META-INF/keycloak-themes.json`
2. changing the directory name in `keycloak-theme/src/main/resources/theme/`
3. changing the theme name in `keycloak-theme/pom.xml`

**Comment by jonkoops** [comment]
If you want to replace the Admin UI theme it should be placed in `lib/lib/main/org.keycloak.keycloak-admin-ui-XXX.jar`. AFAIK we don't support anything else at the moment.

**Comment by jonkoops** [comment]
Closing this issue, as it's not really something we can resolve here.
