### ISSUE TITLE
Identity provider mapping "attribute name" is [object Object]

### ISSUE THREAD

**Issue by libertosurf** [keycloak/keycloak-ui#3724]
### Describe the bug

When trying to add mappers to the Identity provider, upon the save action the "Attribute name" value gets transformed/displayed into [object Object].
Same thing happens if the field is left empty

### Version

19.0.1

### Environment

Chrome 107.0.5304.88

### Expected behavior

Show the proper entered value (or blank if left blank)

### Actual behavior

The value gets replaced by [object Object]

### How to Reproduce?

- Go to identity provider menu
- Mappers
- Create mapper
- Select "Attribute importer"
- fill the Name
- fill the "Attribute name" (or leave it empty)
- fill the "User attribute name" 
- click save
- go to another page, and come back to the details of this mapper
- observe the "attribute name" which is now "[object Object]"

### Anything else?

Not sure if it's only visual as I see that the mapping is not done correctly upon user creation on keycloak when connected to an IDP (= always enters the username regardless of the "Attribute name" I choose (email, firstName, etc...)

**Comment by ssilvert** [comment]
I believe this is fixed in Keycloak 20.0.0.  Can you give that a try and let us know?

**Comment by libertosurf** [comment]
I tried upgrading my server from 19.0.1 to 20.0.1 but it seems like the DB cannot be upgraded because of compatibility issues. Is it really the case or did I do something wrong? 

I extracted the Keycloak server in a new folder, copied/pasted the conf/, providers/, themes/ and data/ from the "old" keycloak; Then, I ran the following command: `kc.bat start-dev --spi-connections-jpa-legacy-migration-strategy=update` but I get this error:

`2022-11-08 09:43:14,038 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Unsupported database file version or invalid file header in file "C:/Tools/keycloak-20.0.1/data/h2/keycloakdb.mv.db" [90048-214]
2022-11-08 09:43:14,038 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Unsupported database file version or invalid file header in file "C:/Tools/keycloak-20.0.1/data/h2/keycloakdb.mv.db" [90048-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
        at org.h2.message.DbException.get(DbException.java:212)
        at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:161)
        at org.h2.mvstore.db.Store.<init>(Store.java:145)
        at org.h2.engine.Database.<init>(Database.java:324)
        at org.h2.engine.Engine.openSession(Engine.java:92)
        at org.h2.engine.Engine.openSession(Engine.java:222)
        at org.h2.engine.Engine.createSession(Engine.java:201)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
        at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:322)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:232)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.h2.mvstore.MVStoreException: The write format 1 is smaller than the supported format 2 [2.1.214/5]
        at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
        at org.h2.mvstore.MVStore.getUnsupportedWriteFormatException(MVStore.java:1066)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:886)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:463)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
        at org.h2.mvstore.db.Store.<init>(Store.java:136)
        ... 15 more`

**Comment by ssilvert** [comment]
@libertosurf Were you able to get past your problem and try this out?  

There should not be any problem upgrading.  I don't know much about that, so I suggest asking in the community.
https://www.keycloak.org/community

**Comment by libertosurf** [comment]
I couldn't get the update to work, but after testing on a fresh install I can confirm that the issue has been fixed in KC 20.0.1
