### ISSUE TITLE
Modify Authentication "X509/Validate Username (Form)" config: HTTP 405 due to RESTEASY003650: No resource method found for PUT, return 405 with Allow header

### ISSUE THREAD

**Issue by psytester** [keycloak/keycloak-ui#3866]
### Describe the bug

1. In Browser flow a new step X509/Validate Username was added and configured.
2. Enter the step settings to modify the config again.
3. Modify a field and revert that change!
4. click save, although nothing was changed

admin ui is using
`PUT http://10.2.56.12:8080/auth/admin/realms/my-realm/authentication/config/`
with payload:
```
{"x509-cert-auth.canonical-dn-enabled":"false","x509-cert-auth.serialnumber-hex-enabled":"false","x509-cert-auth.ocsp-fail-open":"false","x509-cert-auth.regular-expression":"SERIALNUMBER=(.*?)(?:,|$)","x509-cert-auth.crl-checking-enabled":"false","x509-cert-auth.certificate-policy-mode":"All","x509-cert-auth.timestamp-validation-enabled":"true","x509-cert-auth.confirmation-page-disallowed":"false","x509-cert-auth.mapper-selection":"Username or Email","x509-cert-auth.revalidate-certificate-enabled":"true","x509-cert-auth.crldp-checking-enabled":"false","x509-cert-auth.mapping-source-selection":"Match SubjectDN using regular expression","x509-cert-auth.ocsp-checking-enabled":"false","x509-cert-auth.ocsp-responder-uri":"","x509-cert-auth.ocsp-responder-certificate":"","x509-cert-auth.keyusage":"","x509-cert-auth.extendedkeyusage":"","x509-cert-auth.certificate-policy":"","config":{"x509-cert-auth.canonical-dn-enabled":"false","x509-cert-auth.serialnumber-hex-enabled":"false","x509-cert-auth.ocsp-fail-open":"false","x509-cert-auth.regular-expression":"SERIALNUMBER=(.*?)(?:,|$)","x509-cert-auth.crl-checking-enabled":"false","x509-cert-auth.certificate-policy-mode":"All","x509-cert-auth.timestamp-validation-enabled":"true","x509-cert-auth.confirmation-page-disallowed":"false","x509-cert-auth.mapper-selection":"Username or Email","x509-cert-auth.revalidate-certificate-enabled":"true","x509-cert-auth.crldp-checking-enabled":"false","x509-cert-auth.mapping-source-selection":"Match SubjectDN using regular expression","x509-cert-auth.ocsp-checking-enabled":"false","x509-cert-auth.ocsp-responder-uri":"","x509-cert-auth.ocsp-responder-certificate":"","x509-cert-auth.keyusage":"","x509-cert-auth.extendedkeyusage":"","x509-cert-auth.certificate-policy":""}}
```

HTTP 405 Response:
```
{"error":"RESTEASY003650: No resource method found for PUT, return 405 with Allow header"}
```

Notice! it is not the expected endpoint with an id:
`http://10.2.56.12:8080/auth/admin/realms/my-realm/authentication/config/654fc126-9aa0-4df9-90ec-4f9ba22067b9`

related logfile
```
2022-11-24 11:45:20,710 DEBUG [org.keycloak.services.error.KeycloakErrorHandler:69] [executor-thread-98] Error response 405: javax.ws.rs.NotAllowedException: RESTEASY003650: No resource method found for PUT, return 405 with Allow header
        at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:447)
        at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:154)
        at org.jboss.resteasy.core.registry.RootNode.match(RootNode.java:74)
        at org.jboss.resteasy.core.LocatorRegistry.getResourceInvoker(LocatorRegistry.java:83)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:175)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Version

20.0.1

### Environment

Firefox 106.0

**Comment by edewit** [comment]
fixed: #3827
